//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement_Client.UserDataRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DataModelLib")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserDataRef.IUserDataService")]
    public interface IUserDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserDataService/AuthenticateUser", ReplyAction="http://tempuri.org/IUserDataService/AuthenticateUserResponse")]
        string AuthenticateUser(HospitalManagement_Client.UserDataRef.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserDataService/AuthenticateUser", ReplyAction="http://tempuri.org/IUserDataService/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<string> AuthenticateUserAsync(HospitalManagement_Client.UserDataRef.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserDataService/AuthenticateUserById", ReplyAction="http://tempuri.org/IUserDataService/AuthenticateUserByIdResponse")]
        string AuthenticateUserById(HospitalManagement_Client.UserDataRef.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserDataService/AuthenticateUserById", ReplyAction="http://tempuri.org/IUserDataService/AuthenticateUserByIdResponse")]
        System.Threading.Tasks.Task<string> AuthenticateUserByIdAsync(HospitalManagement_Client.UserDataRef.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserDataService/MD5Hash", ReplyAction="http://tempuri.org/IUserDataService/MD5HashResponse")]
        string MD5Hash(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserDataService/MD5Hash", ReplyAction="http://tempuri.org/IUserDataService/MD5HashResponse")]
        System.Threading.Tasks.Task<string> MD5HashAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserDataService/CheckId_replication", ReplyAction="http://tempuri.org/IUserDataService/CheckId_replicationResponse")]
        int CheckId_replication(string Id, string _commandText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserDataService/CheckId_replication", ReplyAction="http://tempuri.org/IUserDataService/CheckId_replicationResponse")]
        System.Threading.Tasks.Task<int> CheckId_replicationAsync(string Id, string _commandText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserDataService/Get_Id", ReplyAction="http://tempuri.org/IUserDataService/Get_IdResponse")]
        string Get_Id(HospitalManagement_Client.UserDataRef.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserDataService/Get_Id", ReplyAction="http://tempuri.org/IUserDataService/Get_IdResponse")]
        System.Threading.Tasks.Task<string> Get_IdAsync(HospitalManagement_Client.UserDataRef.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserDataServiceChannel : HospitalManagement_Client.UserDataRef.IUserDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserDataServiceClient : System.ServiceModel.ClientBase<HospitalManagement_Client.UserDataRef.IUserDataService>, HospitalManagement_Client.UserDataRef.IUserDataService {
        
        public UserDataServiceClient() {
        }
        
        public UserDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AuthenticateUser(HospitalManagement_Client.UserDataRef.User user) {
            return base.Channel.AuthenticateUser(user);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateUserAsync(HospitalManagement_Client.UserDataRef.User user) {
            return base.Channel.AuthenticateUserAsync(user);
        }
        
        public string AuthenticateUserById(HospitalManagement_Client.UserDataRef.User user) {
            return base.Channel.AuthenticateUserById(user);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateUserByIdAsync(HospitalManagement_Client.UserDataRef.User user) {
            return base.Channel.AuthenticateUserByIdAsync(user);
        }
        
        public string MD5Hash(string input) {
            return base.Channel.MD5Hash(input);
        }
        
        public System.Threading.Tasks.Task<string> MD5HashAsync(string input) {
            return base.Channel.MD5HashAsync(input);
        }
        
        public int CheckId_replication(string Id, string _commandText) {
            return base.Channel.CheckId_replication(Id, _commandText);
        }
        
        public System.Threading.Tasks.Task<int> CheckId_replicationAsync(string Id, string _commandText) {
            return base.Channel.CheckId_replicationAsync(Id, _commandText);
        }
        
        public string Get_Id(HospitalManagement_Client.UserDataRef.User user) {
            return base.Channel.Get_Id(user);
        }
        
        public System.Threading.Tasks.Task<string> Get_IdAsync(HospitalManagement_Client.UserDataRef.User user) {
            return base.Channel.Get_IdAsync(user);
        }
    }
}
